; SUM OF EVEN OF NUMBERS IN ARRAY SIZE OF 10

MOV SI, 1000H ;1000 IS LOCATION OF SI
MOV DI, 2000H ;2000 IS LOCATION OF DI
MOV DL, 0000  ;SUMMING REGISTER 
MOV CL, 010
MOV BL,02   ;COUNT OF ARRAY
   ;LOOP 1      
L1:      
MOV AL, [SI]; LOADING $SI VALUE INTO AL

DIV BL
CMP AH,0
JNZ L2     

ADD DL,[SI]

L2:
INC SI      ; INCREASING SI VALUE 
DEC CL      ; DECREASING CL VALUE
JNZ L1      ; JUMP INTO L1 UNTIL CL ==0

MOV [DI],DL ; ANSWER IS LOADED INTO DESITINATION INDEX 
HLT